"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "./safe-link";
import { ArrowUpRight, MapPin, Briefcase, Clock, Check, MagnifyingGlass } from "@phosphor-icons/react";
import { companies, occupations, opportunities } from "../data/labor-market.ts";
import { getJourney, minimumFor, money, opportunityLinks, participantProfile } from "../domain/guidance.ts";
import { ErrorNotice, initials, Loading, Shell } from "./shared";
import { Metric, PageHeading, PanelHeading } from "./analytics-shared";
import { useDemo } from "./use-demo";

export default function CompaniesScreen(){
  const demo=useDemo();const {state,loading,error}=demo;const params=useSearchParams();
  const [query,setQuery]=useState("");const [occupation,setOccupation]=useState("");const [selectedId,setSelectedId]=useState<string|null>(null);
  const [tab,setTab]=useState<"conditions"|"connections">("connections");
  const normalize=(text:string)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const offers=opportunities.filter(offer=>(!occupation||offer.occupation===occupation)&&normalize(`${offer.title} ${companies.find(company=>company.id===offer.companyId)!.name}`).includes(normalize(query)));
  const selected=offers.find(offer=>offer.id===(selectedId??params.get("oferta")))??offers[0];
  const company=companies.find(item=>item.id===selected?.companyId);
  const links=selected?(state?.participants??[]).flatMap(person=>{const journey=getJourney(state!,person);if(!journey)return [];const link=opportunityLinks(journey.answers,participantProfile(person)).find(item=>item.opportunity.id===selected.id);return link?[{person,journey,...link}]:[];}):[];
  const minimum=selected?minimumFor(selected.region,selected.economicActivity):null;
  return <Shell viewRole="team"><PageHeading eyebrow="RELACIONES QUE ABREN CAMINOS" title="Empresas y oportunidades" description="Conecta los intereses de las personas con lo que las empresas necesitan."/>
    {error&&<ErrorNotice message={error} retry={demo.retry}/>}{loading?<Loading/>:state&&<>
      <div className="metrics-grid three"><Metric label="Empresas del escenario" value={new Set(offers.map(offer=>offer.companyId)).size} detail="Organizaciones ficticias"/><Metric label="Oportunidades" value={offers.length} detail="Puestos para explorar en el filtro actual"/><Metric label="Plazas simuladas" value={offers.reduce((count,offer)=>count+offer.openings,0)} detail="No son vacantes publicadas" accent/></div>
      <div className="company-layout"><section className="panel opportunity-directory"><PanelHeading title="Directorio de oportunidades" description="Selecciona un puesto para ver sus conexiones."/><div className="directory-filters"><label className="search-field"><span className="sr-only">Buscar empresa o puesto</span><MagnifyingGlass size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Empresa o puesto…" type="search"/></label><label><span className="sr-only">Ocupación</span><select value={occupation} onChange={event=>setOccupation(event.target.value)}><option value="">Todas las ocupaciones</option>{occupations.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><div className="opportunity-directory-list">{offers.map(offer=>{const owner=companies.find(item=>item.id===offer.companyId)!;return <button className={`directory-item ${selected?.id===offer.id?"active":""}`} key={offer.id} onClick={()=>setSelectedId(offer.id)} aria-pressed={selected?.id===offer.id}><span className={`company-avatar ${owner.color}`}>{owner.initials}</span><span><strong>{offer.title}</strong><small>{owner.name} · {owner.municipality}</small><span className="directory-pay">{money(offer.baseMin,offer.baseMin%1?2:0)}<span> base · {offer.openings} plazas</span></span></span><ArrowUpRight size={15}/></button>;})}{!offers.length&&<div className="empty-inline"><strong>No encontramos oportunidades.</strong><p>Prueba otra búsqueda u ocupación.</p><button className="text-button" onClick={()=>{setQuery("");setOccupation("");}}>Limpiar filtros</button></div>}</div></section>
      {selected&&company&&minimum&&<section className="panel company-detail"><div className="company-cover"><span className={`company-avatar xl ${company.color}`}>{company.initials}</span><span className="badge neutral">EMPRESA FICTICIA</span></div><div className="company-detail-heading"><p className="eyebrow">{company.name} · {company.sector}</p><h2>{selected.title}</h2><p>{company.description}</p><div className="meta-chips"><span><MapPin size={15}/>{company.municipality}</span><span><Clock size={15}/>{selected.schedule}</span><span><Briefcase size={15}/>{selected.minMonths?`${selected.minMonths} meses solicitados`:"Sin experiencia previa"}</span></div></div><div className="offer-compensation"><div><span>Oferta base mensual</span><strong>{money(selected.baseMin,selected.baseMin%1?2:0)}{selected.baseMin!==selected.baseMax?` – ${money(selected.baseMax)}`:""}</strong><small>+ {money(selected.incentive)} de bonificación incentivo</small></div><div><span>Referencia {minimum.label.toLowerCase()} · {selected.region}</span><strong>{money(minimum.base,2)}</strong><small>Mínimo base mensual 2026</small></div></div><div className="detail-tabs"><button className={tab==="connections"?"active":""} aria-pressed={tab==="connections"} onClick={()=>setTab("connections")}>Conexiones para conversar <span className="count-tag">{links.length}</span></button><button className={tab==="conditions"?"active":""} aria-pressed={tab==="conditions"} onClick={()=>setTab("conditions")}>Condiciones del puesto</button></div>
      {tab==="connections"?<div className="company-connections"><p className="small muted">Estas personas comparten interés en la ocupación. La lista no puntúa capacidades ni confirma una selección.</p>{links.map(({person,journey,reasons,pending})=><article className="connection-person" key={person.id}><div className="connection-heading"><Link className="person-cell" href={`/equipo/participantes?persona=${person.id}`}><span className="avatar">{initials(person.name)}</span><span><strong>{person.name}</strong><small>{person.municipality} · {journey.answers.experienceMonths||"Sin indicar"}{journey.answers.experienceMonths!==""?" meses de experiencia":""}</small></span></Link><Link className="inline-link" href={`/equipo/rutas?persona=${person.id}`}>Ver ruta<ArrowUpRight size={14}/></Link></div><div className="connection-facts"><span>Expectativa base <strong>{journey.answers.expectedSalary?money(+journey.answers.expectedSalary):"Por conversar"}</strong></span><span>Disponibilidad <strong>{participantProfile(person)?.availability||"Por definir"}</strong></span></div><div className="reasons-inline">{reasons.map(reason=><span key={reason}><Check size={13}/>{reason}</span>)}</div><details><summary>{pending.length} aspectos por conversar</summary><ul>{pending.map(item=><li key={item}>{item}</li>)}</ul></details></article>)}{!links.length&&<div className="empty-inline">Aún no hay participantes con esta ocupación de interés. Puedes completar otro cuestionario desde la vista participante.</div>}</div>:<div className="company-conditions"><h3>Lo que busca este escenario</h3><ul>{selected.requirements.map(item=><li key={item}>{item}</li>)}</ul><div className="method-note"><strong>Contexto de la oferta</strong><p>{selected.note}</p></div><p>Centro de trabajo: {company.municipality}, departamento de Guatemala. {selected.openings} plazas ficticias de jornada completa.</p><Link className="inline-link" href={`/equipo/salarios?oferta=${selected.id}`}>Comparar salario y referencia oficial<ArrowUpRight size={15}/></Link></div>}
      </section>}</div>
    </>}
  </Shell>;
}
