"use client";
import Link from "./safe-link";
import { ArrowUpRight, SlidersHorizontal, ArrowRight, Users, Buildings, Briefcase, FileText } from "@phosphor-icons/react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { companies, occupations, opportunities, occupationLabel } from "../data/labor-market.ts";
import { config } from "../domain/config.ts";
import { average, getJourney, median, money, participantProfile } from "../domain/guidance.ts";
import { messageFrom, useDemo } from "./use-demo";
import type { DashboardFilters } from "../domain/types.ts";
import { ErrorNotice, initials, Loading, Shell, StatusBadge } from "./shared";
import { ChartLegend, EmptyChart, ExportButton, Metric, PageHeading, PanelHeading } from "./analytics-shared";

export default function DashboardScreen(){
  const demo=useDemo();const {state,loading,error}=demo;
  const {program="",city="",occupation="",status=""}=state?.dashboardFilters??{};
  function saveFilters(filters:Partial<DashboardFilters>){try{demo.run(repo=>repo.saveDashboardFilters(filters));}catch(cause){demo.setError(messageFrom(cause));}}
  const setProgram=(program:string)=>saveFilters({program});const setCity=(city:string)=>saveFilters({city});const setOccupation=(occupation:string)=>saveFilters({occupation});const setStatus=(status:string)=>saveFilters({status});
  const people=(state?.participants??[]).filter(person=>(!program||person.enrollment.programId===program)&&(!city||person.municipality===city)&&(!occupation||getJourney(state!,person)?.answers.occupation===occupation)&&(!status||person.enrollment.status===status));
  const offers=opportunities.filter(offer=>(!occupation||offer.occupation===occupation)&&(!city||companies.find(company=>company.id===offer.companyId)?.municipality===city));
  const sharedOffers=offers.filter(offer=>people.some(person=>getJourney(state!,person)?.answers.occupation===offer.occupation));
  const demand=occupations.filter(item=>!occupation||item.id===occupation).map(item=>({id:item.id,name:item.label,participants:people.filter(person=>getJourney(state!,person)?.answers.occupation===item.id).length,openings:offers.filter(offer=>offer.occupation===item.id).reduce((n,offer)=>n+offer.openings,0)}));
  const salaries=occupations.filter(item=>!occupation||item.id===occupation).map(item=>({name:item.label,expectation:median(people.filter(person=>getJourney(state!,person)?.answers.occupation===item.id&&participantProfile(person)?.availability==="Tiempo completo").map(person=>getJourney(state!,person)!.answers.expectedSalary).filter(Boolean).map(Number)),offer:average(offers.filter(offer=>offer.occupation===item.id).map(offer=>offer.baseMin))}));
  const missingCV=people.filter(person=>getJourney(state!,person)?.answers.cvUpdated==="No").length;
  const attention=people.filter(person=>getJourney(state!,person)?.steps.some(step=>step.status!=="completado"));
  const filtered=!!(program||city||occupation||status);
  const rows=[['Participante ficticia','Municipio','Ocupación','Estado','Expectativa base GTQ','Disponibilidad'],...people.map(person=>[person.name,person.municipality,occupationLabel(getJourney(state!,person)?.answers.occupation??""),config.states.find(item=>item.id===person.enrollment.status)!.label,getJourney(state!,person)?.answers.expectedSalary??"",participantProfile(person)?.availability??""])];
  return <Shell viewRole="team"><PageHeading eyebrow="INTELIGENCIA PARA EL ACOMPAÑAMIENTO" title="El talento, en perspectiva." description="Personas, oportunidades y próximos pasos en un mismo lugar."><ExportButton rows={rows} filename="talentia-participantes-demo.csv"/></PageHeading>
    {error&&<ErrorNotice message={error} retry={demo.retry}/>}{loading?<Loading/>:state&&<>
      <div className="dashboard-filters"><span className="filter-caption"><SlidersHorizontal size={17}/>Explorar</span><label><span className="sr-only">Programa del panel</span><select value={program} onChange={event=>setProgram(event.target.value)}><option value="">Todos los programas</option>{config.programs.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span className="sr-only">Municipio del panel</span><select value={city} onChange={event=>setCity(event.target.value)}><option value="">Todos los municipios</option>{config.municipalities.map(item=><option key={item}>{item}</option>)}</select></label><label><span className="sr-only">Ocupación del panel</span><select value={occupation} onChange={event=>setOccupation(event.target.value)}><option value="">Todas las ocupaciones</option>{occupations.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{filtered&&<button className="text-button" onClick={()=>{saveFilters({program:"",city:"",occupation:"",status:""});}}>Limpiar filtros</button>}<span className="snapshot-label">Escenario · Septiembre 2026</span></div>
      <div className="metrics-grid four"><Metric label="Participantes" value={people.length} detail={`${state.participants.length} expedientes en la demo`} accent><Users size={22}/></Metric><Metric label="Empresas con conexiones" value={new Set(sharedOffers.map(offer=>offer.companyId)).size} detail="Por ocupación de interés compartida"><Buildings size={22}/></Metric><Metric label="Plazas para explorar" value={sharedOffers.reduce((n,offer)=>n+offer.openings,0)} detail={`${sharedOffers.length} oportunidades ficticias relacionadas`}><Briefcase size={22}/></Metric><Metric label="Sin CV actualizado" value={missingCV} detail="Según respuestas del cuestionario"><FileText size={22}/></Metric></div>
      <div className="dashboard-grid"><section className="panel demand-panel"><PanelHeading title="¿Dónde se encuentran talento y demanda?" description="Participantes por interés y plazas de las empresas del escenario." href="/equipo/empresas"/><ChartLegend items={[{label:"Participantes",color:"#4665e7"},{label:"Plazas ficticias",color:"#b9c8f7"}]}/><div className="chart-container" role="img" aria-label={demand.map(row=>`${row.name}: ${row.participants} participantes, ${row.openings} plazas`).join("; ")}>{demand.length?<ResponsiveContainer width="100%" height={286}><BarChart data={demand} layout="vertical" barGap={3} margin={{top:6,right:24,bottom:0,left:0}}><CartesianGrid horizontal={false} stroke="#edf0f5"/><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} tick={{fontSize:11,fill:"#7b8190"}}/><YAxis dataKey="name" type="category" width={136} tickLine={false} axisLine={false} tick={{fontSize:12,fill:"#515a70"}}/><Tooltip cursor={{fill:"#f5f7fc"}} contentStyle={{borderRadius:8,border:"1px solid #e6e9ef",fontSize:12}}/><Bar name="Participantes" dataKey="participants" fill="#4665e7" radius={[0,3,3,0]} maxBarSize={11} isAnimationActive={false}/><Bar name="Plazas ficticias" dataKey="openings" fill="#b9c8f7" radius={[0,3,3,0]} maxBarSize={11} isAnimationActive={false}/></BarChart></ResponsiveContainer>:<EmptyChart/>}</div><p className="chart-footnote">Una conexión indica interés compartido; quedan experiencia, condiciones y disponibilidad por conversar.</p></section>
      <section className="panel stage-panel"><PanelHeading title="Momento del acompañamiento" description="Estado registrado por el equipo."/><div className="stage-list">{config.states.map((item,index)=>{
        const count=people.filter(person=>person.enrollment.status===item.id).length;
        return <button key={item.id} aria-pressed={status===item.id} className={`stage-row ${status===item.id?"active":""}`} onClick={()=>setStatus(status===item.id?"":item.id)}><span className="stage-index">0{index+1}</span><span className="stage-name">{item.label}<span className="stage-track"><i style={{width:`${people.length?count/people.length*100:0}%`}}/></span></span><strong>{count}</strong></button>;
      })}</div><p className="chart-footnote">Selecciona un estado para filtrar el panel. Los estados de muestra no acreditan resultados reales.</p></section>
      <section className="panel"><PanelHeading title="La conversación salarial" description="Expectativa mediana y promedio de las bases iniciales ofrecidas." href="/equipo/salarios" link="Ver observatorio"/><ChartLegend items={[{label:"Expectativa base",color:"#4665e7"},{label:"Oferta base inicial",color:"#28a28a"}]}/><div className="chart-container" role="img" aria-label={salaries.map(row=>`${row.name}: expectativa ${row.expectation===null?"sin datos":money(row.expectation)}, oferta ${row.offer===null?"sin datos":money(row.offer)}`).join("; ")}><ResponsiveContainer width="100%" height={265}><BarChart data={salaries} margin={{top:12,right:16,bottom:10,left:0}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{fontSize:10,fill:"#6d7688"}} interval={0} angle={-18} textAnchor="end" height={55}/><YAxis tickFormatter={value=>`${value/1000} mil`} tickLine={false} axisLine={false} width={45} tick={{fontSize:11,fill:"#7b8190"}}/><Tooltip formatter={value=>money(Number(value),2)} cursor={{fill:"#f5f7fc"}} contentStyle={{borderRadius:8,border:"1px solid #e6e9ef",fontSize:12}}/><Bar name="Expectativa base" dataKey="expectation" fill="#4665e7" radius={[3,3,0,0]} maxBarSize={17} isAnimationActive={false}/><Bar name="Oferta base inicial" dataKey="offer" fill="#28a28a" radius={[3,3,0,0]} maxBarSize={17} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="chart-footnote">GTQ / mes, sin incentivo. Expectativas con jornada completa; las demás jornadas quedan fuera. Ofertas ficticias, no salarios de mercado.</p></section>
      <section className="panel"><PanelHeading title="El siguiente paso tiene nombre" description={`${attention.length} personas con actividades pendientes en su ruta.`} href="/equipo/rutas" link="Ver rutas"/><div className="attention-list">{attention.slice(0,4).map(person=>{
        const journey=getJourney(state,person)!;const next=journey.steps.find(step=>step.status!=="completado")!;
        return <Link className="attention-row" key={person.id} href={`/equipo/rutas?persona=${person.id}`}><span className="avatar">{initials(person.name)}</span><span><strong>{person.name}</strong><small>{next.title}</small></span><ArrowUpRight size={16}/></Link>;
      })}{!attention.length&&<div className="empty-inline">No hay actividades pendientes con estos filtros.</div>}</div><div className="case-callout"><span className="case-number">CASO 01</span><div><strong>Julia quiere empezar como barista.</strong><p>Del cuestionario a una ruta concreta y una conversación salarial.</p><Link href="/equipo/rutas?persona=p010">Recorrer su historia<ArrowRight size={15}/></Link></div></div></section></div>
      <section className="panel overview-table"><PanelHeading title="Personas detrás de los indicadores" description="Abre un expediente para entender su contexto y acompañar su ruta." href="/equipo/participantes" link="Todos los expedientes"/><div className="table-scroll"><table><caption className="sr-only">Participantes de los filtros actuales</caption><thead><tr><th>Participante</th><th>Interés laboral</th><th>Expectativa base / mes</th><th>Estado</th><th>Ruta</th></tr></thead><tbody>{people.map(person=>{const journey=getJourney(state,person);return <tr key={person.id}><td><Link className="person-cell" href={`/equipo/participantes?persona=${person.id}`}><span className="avatar">{initials(person.name)}</span><span><strong>{person.name}</strong><small>{person.municipality}</small></span></Link></td><td>{occupationLabel(journey?.answers.occupation??"")}</td><td className="numeric">{journey?.answers.expectedSalary?money(+journey.answers.expectedSalary):"Por conversar"}<small className="cell-subtext">{participantProfile(person)?.availability||"Jornada por definir"}</small></td><td><StatusBadge status={person.enrollment.status}/></td><td><Link className="inline-link" href={`/equipo/rutas?persona=${person.id}`}>{journey?`${journey.steps.filter(step=>step.status==="completado").length}/${journey.steps.length} pasos`:"Por iniciar"}<ArrowUpRight size={14}/></Link></td></tr>;})}</tbody></table>{!people.length&&<EmptyChart/>}</div></section>
      <p className="data-caption">Datos ficticios de demostración + cambios guardados en este navegador. Los indicadores se calculan sobre la selección actual.</p>
    </>}
  </Shell>;
}

