"use client";
import { useState, type FormEvent } from "react";
import Link from "./safe-link";
import { ArrowRight, ArrowUpRight, Check, CheckCircle, Path, PencilSimple } from "@phosphor-icons/react";
import { occupations, occupationLabel, scenarios } from "../data/labor-market.ts";
import { getJourney, initialAnswers, money, participantProfile, questionnaireFields } from "../domain/guidance.ts";
import type { DemoState, Participant, Questionnaire, StepStatus } from "../domain/types.ts";
import { formatDate } from "./shared";
import { OpportunitiesForPerson } from "./analytics-shared";
import { messageFrom, useDemo } from "./use-demo";
type DemoHook=ReturnType<typeof useDemo>;

export function QuestionnaireForm({demo,state,person,done}:{demo:DemoHook;state:DemoState;person:Participant;done:()=>void}){
  const [failedDraft,setFailedDraft]=useState<Partial<Questionnaire>|null>(null);const [confirmed,setConfirmed]=useState(false);
  const saved=getJourney(state,person);
  const unsaved=demo.hasPendingDraft?failedDraft:null;
  const draft={...(state.questionnaireDrafts?.[person.id]??saved?.answers??initialAnswers(person)),...unsaved};
  const needsConfirmation=!!(saved?.reviewedAt||saved?.steps.some(step=>step.status!=="pendiente"));
  function change(key:keyof Questionnaire,value:string){const next={...unsaved,[key]:value};setConfirmed(false);try{demo.run(repo=>repo.saveQuestionnaireDraft(person.id,next),true);setFailedDraft(null);}catch(cause){setFailedDraft(next);demo.setError(messageFrom(cause));}}
  function submit(event:FormEvent){event.preventDefault();if(needsConfirmation&&!confirmed)return;try{demo.run(repo=>repo.saveQuestionnaire(person.id,draft));done();}catch(cause){demo.setError(messageFrom(cause));}}
  return <form className="form-card questionnaire-form" onSubmit={submit}><div className="form-card-header"><span className="eyebrow">CONOCER PARA ACOMPAÑAR</span><h2>¿Hacia dónde quieres ir?</h2><p>Tus respuestas ayudan a preparar una propuesta de ruta. Puedes dejar cualquier pregunta pendiente.</p></div><div className="field-grid"><label className="field wide">Trabajo que te interesa<select value={draft.occupation} onChange={event=>change("occupation",event.target.value)}><option value="">Quiero explorar opciones</option>{occupations.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="field">Expectativa de salario base mensual (Q)<input type="number" min="0.01" max="100000" step="0.01" value={draft.expectedSalary} onChange={event=>change("expectedSalary",event.target.value)} placeholder="Ejemplo: 4500"/><span className="field-hint">Sin bonificación incentivo. Para tu disponibilidad: {participantProfile(person)?.availability||"por definir"}. No es tu ingreso actual.</span></label><label className="field">Meses de experiencia en esta ocupación<input type="number" min="0" max="600" step="1" value={draft.experienceMonths} onChange={event=>change("experienceMonths",event.target.value)} placeholder="0 si estás comenzando"/><span className="field-hint">Incluye prácticas o experiencia informal, identificándolas en tu perfil.</span></label>{questionnaireFields.map(field=><label className="field" key={field.key}>{field.label}<select value={draft[field.key]} onChange={event=>change(field.key,event.target.value)}><option value="">Lo conversaré después</option>{field.options.map(option=><option key={option}>{option}</option>)}</select></label>)}</div>{needsConfirmation&&<div className="consent-box"><label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>Preparar una nueva ruta y reiniciar el avance de sus actividades. La revisión anterior quedará pendiente.</span></label><p>Tu perfil y el historial de estados se conservan.</p></div>}<div className="form-actions"><span className="small muted">El equipo revisa la propuesta contigo.</span><button className="button primary" disabled={needsConfirmation&&!confirmed}>Preparar mi ruta<ArrowRight size={16}/></button></div></form>;
}

export function JourneyView({demo,state,person,team=false,onEdit}:{demo:DemoHook;state:DemoState;person:Participant;team?:boolean;onEdit?:()=>void}){
  const journey=getJourney(state,person);const profile=participantProfile(person);const [notice,setNotice]=useState("");const [tab,setTab]=useState<"route"|"opportunities">("route");
  if(!journey)return <div className="empty-state"><Path size={32}/><h3>El próximo paso es conversar.</h3><p>Completa el cuestionario de esta persona para preparar una ruta y explorar oportunidades.</p>{onEdit?<button className="button primary" onClick={onEdit}>Completar cuestionario<ArrowRight size={16}/></button>:<Link className="button secondary" href="/participante" onClick={event=>{try{demo.run(repo=>repo.selectParticipant(person.id));}catch(cause){event.preventDefault();demo.setError(messageFrom(cause));}}}>Abrir vista participante</Link>}</div>;
  const completed=journey.steps.filter(step=>step.status==="completado").length;
  const isScenario=person.source==="sample"&&!state.journeys?.[person.id];
  function update(id:string,status:StepStatus){try{demo.run(repo=>repo.updateRouteStep(person.id,id,status));setNotice("Actividad actualizada. La propuesta queda disponible para revisión del equipo.");}catch(cause){demo.setError(messageFrom(cause));}}
  function review(){try{demo.run(repo=>repo.reviewRoute(person.id));setNotice("Revisión registrada por Equipo demo. No se envió ninguna postulación.");}catch(cause){demo.setError(messageFrom(cause));}}
  return <div className="journey-workspace"><div className="journey-summary"><div><span className="eyebrow">{isScenario?"RUTA DE EJEMPLO · DATOS FICTICIOS":"PROPUESTA DE ACOMPAÑAMIENTO"}</span><h2>Un camino hacia {occupationLabel(journey.answers.occupation).toLowerCase()}.</h2><p>{profile?.objective||scenarios[person.id]?.story||"Construyamos un próximo paso a partir de tus intereses."}</p></div><div className="journey-progress"><strong>{completed}<span> / {journey.steps.length}</span></strong><span>actividades completadas</span><progress value={completed} max={journey.steps.length} aria-label="Avance de actividades"/></div></div>
    <div className="journey-facts"><div><span>Interés</span><strong>{occupationLabel(journey.answers.occupation)}</strong></div><div><span>Experiencia declarada</span><strong>{journey.answers.experienceMonths!==""?`${journey.answers.experienceMonths} meses`:"Por conversar"}</strong></div><div><span>Expectativa base / mes</span><strong>{journey.answers.expectedSalary?money(+journey.answers.expectedSalary):"Por conversar"}</strong></div><div><span>Disponibilidad</span><strong>{profile?.availability||"Por definir"}</strong></div></div>
    {notice&&<div className="notice success-notice" role="status">{notice}</div>}
    <div className="detail-tabs"><button className={tab==="route"?"active":""} aria-pressed={tab==="route"} onClick={()=>setTab("route")}>Ruta de acompañamiento</button><button className={tab==="opportunities"?"active":""} aria-pressed={tab==="opportunities"} onClick={()=>setTab("opportunities")}>Oportunidades para conversar</button>{onEdit&&<button className="edit-answers" onClick={onEdit}><PencilSimple size={14}/>Editar respuestas</button>}</div>
    {tab==="route"?<div className="journey-content"><ol className="route-steps">{journey.steps.map((step,index)=><li key={step.id} className={`route-step ${step.status}`}><span className="route-marker">{step.status==="completado"?<Check size={16} weight="bold"/>:String(index+1).padStart(2,"0")}</span><div className="route-step-content"><div className="route-step-heading"><div><span className="step-owner">{step.owner}</span><h3>{step.title}</h3></div>{step.id!=="revision"?<label className="step-state"><span className="sr-only">Estado de {step.title}</span><select value={step.status} onChange={event=>update(step.id,event.target.value as StepStatus)}><option value="pendiente">Pendiente</option><option value="en_proceso">En proceso</option><option value="completado">Completado</option></select></label>:<span className={`badge ${journey.reviewedAt?"green":"amber"}`}>{journey.reviewedAt?"Revisada":"Por revisar"}</span>}</div><p>{step.action}</p><div className="why-step"><strong>Por qué este paso</strong><span>{step.reason}</span></div></div></li>)}</ol><div className={`route-review ${journey.reviewedAt?"reviewed":""}`}><CheckCircle size={26}/><div><strong>{journey.reviewedAt?"Propuesta revisada por el equipo":"La orientación se construye contigo"}</strong><p>{journey.reviewedAt?`${journey.reviewedBy} · ${formatDate(journey.reviewedAt)}`:"Esta ruta se basa en las respuestas del cuestionario. El equipo y la participante confirman los pasos y las condiciones."}</p></div>{team&&!journey.reviewedAt&&<button className="button primary" onClick={review}>Registrar revisión<Check size={16}/></button>}</div></div>:<div className="journey-content"><OpportunitiesForPerson answers={journey.answers} profile={profile}/><Link className="inline-link salary-route-link" href="/equipo/salarios">Explorar referencias salariales<ArrowUpRight size={15}/></Link></div>}
  </div>;
}
